## Main
#
# Initialize CMUtil module.
#

CMAKE_MINIMUM_REQUIRED(VERSION 3.18 FATAL_ERROR)

SET(CMUTIL_PACKAGE_NAME "CMUTIL")

SET(${CMUTIL_PACKAGE_NAME}_FOUND 1)
SET(${CMUTIL_PACKAGE_NAME}_DIR "${CMAKE_CURRENT_LIST_DIR}")

INCLUDE_GUARD(GLOBAL)

FIND_PACKAGE(CMLIB REQUIRED)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMUTIL_TRAIT.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMUTIL_PROPERTY_FILE.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMUTIL_VERSION.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMUTIL_PLATFORM_STRING.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMUTIL_NORMALIZE_GIT_URI.cmake)

